image: go1.2
env:
  - GOPATH=/var/cache/drone
services:
  - mongodb
script:
  - pwd
  - ls -ltr
  - go build main.go
  - go get labix.org/v2/mgo
  - go get labix.org/v2/mgo/bson
  - go build
  - go test -cover -v
git:
  depth: 1
test: {{test_key}}

