image: go1.2
env:
  - GOPATH=/var/cache/drone
services:
  - mongoXXX bradrydzewski/mongodb:2.2 27017
  - abc yosssi/lamp
script:
  - go get labix.org/v2/mgo
  - go get labix.org/v2/mgo/bson
  - go build
  - go test -cover -v
git:
  depth: 1
