image: go1.2
env:
  - GOPATH=/var/cache/drone
customServices:
  mongodb:
    tag: bradrydzewski/mongodb:2.4
    ports:
      - 27017
script:
  - go get labix.org/v2/mgo
  - go get labix.org/v2/mgo/bson
  - go build
  - go test -cover -v
git:
  depth: 1
